### PR TITLE
Testing on Linux and OSX via Travis CI

### PR DESCRIPTION
**Pull request by Psiablo**
## Status: Complete
- [x] Run tests on both Linux and OS X
- [x] Run tests on multiple node version for both os.
- [x] Run on Travis CI's new Docker instance on Linux for faster builds. (`sudo:false`).

### CODE REVIEW

**Comment by Psiablo** [comment]
@nfroidure can we get a "WIP" label for this?

**Comment by nfroidure** [comment]
Just linking the issue to stay aware of its resolution https://github.com/travis-ci/travis-ci/issues/2311

**Comment by Psiablo** [comment]
Thanks for linking. There actually is some really good notes from others in that issue. I'm going to modify some things in the morning.

**Comment by Psiablo** [comment]
@nfroidure This should be ready for merge on CI completion.

**Comment by Psiablo** [comment]
:ship:

**Pull request merged**
