### PR TITLE
Disable Emscripten NODEJS_CATCH_EXIT and NODEJS_CATCH_REJECTION flags

### PR DESCRIPTION
**Pull request by andersk**
When using ttf2woff2 as a library (e.g. inside webfonts-loader), this was previously catching promise rejections from other code that had nothing to do with ttf2woff2.

See https://github.com/emscripten-core/emscripten/issues/7855.

### Proposed changes
- Add `-s NODEJS_CATCH_EXIT=0 -s NODEJS_CATCH_REJECTION=0` to `emcc` arguments.

### Code quality
- [ ] I made some tests for my changes
- [x] I added my name in the
 [contributors](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
 field of the `package.json` file. Beware to use the same format than for the author field
 for the entries so that you'll get a mention in the `README.md` with a link to your website.

### License
To get your contribution merged, you must check the following.

- [x] I read the project license in the LICENSE file
- [x] I agree with publishing under this project license

### Join
- [ ] I wish to join the core team
- [x] I agree that with great powers comes responsibilities
- [x] I'm a nice person

My NPM username: andersk

### CODE REVIEW

**Comment by nfroidure** [comment]
@andersk thanks for contributing. I feel like your change won't have any breaking impact on the existing users so I think I'll make a major version.

**Comment by andersk** [comment]
I agree it’s non-breaking. But surely you mean minor or patch, not major?

**Comment by nfroidure** [comment]
I meant major, when I'n not sure I won't break things, I prefer spawn a major than take the risk to break other's build.

**Comment by andersk** [comment]
I’d prefer a minor release, if possible; it took a lot of time to propagate the last major release all the way through the dependency chain (@vusion/webfonts-generator and then webfonts-loader).

**Comment by andersk** [comment]
Here is the entire beautified diff to `jssrc/ttf2woff2.js`, so you can see that the only change is to remove the handlers that abort on exceptions. (I compiled with exactly the same version of Emscripten to ensure that this diff would be small.) Removing an abort cannot break someone’s build.

```diff
@@ -60,12 +60,6 @@
   if (typeof module !== 'undefined') {
     module['exports'] = Module;
   }
-  process['on']('uncaughtException', function (ex) {
-    if (!(ex instanceof ExitStatus)) {
-      throw ex;
-    }
-  });
-  process['on']('unhandledRejection', abort);
   quit_ = function (status) {
     process['exit'](status);
   };
@@ -1695,11 +1689,6 @@
 Module['getValue'] = getValue;
 Module['writeArrayToMemory'] = writeArrayToMemory;
 var calledRun;
-function ExitStatus(status) {
-  this.name = 'ExitStatus';
-  this.message = 'Program terminated with exit(' + status + ')';
-  this.status = status;
-}
 dependenciesFulfilled = function runCaller() {
   if (!calledRun) run();
   if (!calledRun) dependenciesFulfilled = runCaller;
```

**Comment by nfroidure** [comment]
Ok, so let's release a patch then and cross fingers :P.

**Pull request merged**
